package color

var (
	csi      = []byte("\x1b[")
	preFg256 = []byte(";38;5;")
	preBg256 = []byte(";48;5;")
)

// is []byte necessary?
var attr = map[string][]byte{
	"reset":           []byte(";0"),
	"bold":            []byte(";1"),
	"faint":           []byte(";2"),
	"italic":          []byte(";3"),
	"underline":       []byte(";4"),
	"blink":           []byte(";5"),
	"inverse":         []byte(";7"),
	"invisible":       []byte(";8"),
	"crossedOut":      []byte(";9"),
	"doubleUnderline": []byte(";21"),
	"normal":          []byte(";22"),
	"notItalic":       []byte(";23"),
	"notUnderlined":   []byte(";24"),
	"steady":          []byte(";25"),
	"positive":        []byte(";27"),
	"visible":         []byte(";28"),
	"notCrossedOut":   []byte(";29"),
	"fgBlack":         []byte(";30"),
	"fgRed":           []byte(";31"),
	"fgGreen":         []byte(";32"),
	"fgYellow":        []byte(";33"),
	"fgBlue":          []byte(";34"),
	"fgMagenta":       []byte(";35"),
	"fgCyan":          []byte(";36"),
	"fgWhite":         []byte(";37"),
	"fgDefault":       []byte(";39"),
	"bgBlack":         []byte(";40"),
	"bgRed":           []byte(";41"),
	"bgGreen":         []byte(";42"),
	"bgYellow":        []byte(";43"),
	"bgBlue":          []byte(";44"),
	"bgMagenta":       []byte(";45"),
	"bgCyan":          []byte(";46"),
	"bgWhite":         []byte(";47"),
	"bgDefault":       []byte(";49"),
	"fgBrightBlack":   []byte(";90"),
	"fgBrightRed":     []byte(";91"),
	"fgBrightGreen":   []byte(";92"),
	"fgBrightYellow":  []byte(";93"),
	"fgBrightBlue":    []byte(";94"),
	"fgBrightMagenta": []byte(";95"),
	"fgBrightCyan":    []byte(";96"),
	"fgBrightWhite":   []byte(";97"),
	"bgBrightBlack":   []byte(";100"),
	"bgBrightRed":     []byte(";101"),
	"bgBrightGreen":   []byte(";102"),
	"bgBrightYellow":  []byte(";103;"),
	"bgBrightBlue":    []byte(";104"),
	"bgBrightMagenta": []byte(";105"),
	"bgBrightCyan":    []byte(";106"),
	"bgBrightWhite":   []byte(";107"),
}
